#!/bin/bash

build() {
    add_file "/etc/splash.conf"
    add_file "/lib/splash/splash.jpg"
    add_binary "/sbin/splash"
    
    add_runscript
}

help() {
    cat <<HELPEOF
This hook will use trigger boot splash.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
