#!/usr/bin/ash

run_earlyhook() {
    msg " * Loading modules..."
    modprobe nvidiafb uvesafb
    msg " * Initiating ssplash..."
    ssplash /etc/ssplash.conf
}

run_hook() {
    msg " * Sending message to ssplash..."
}

run_cleanuphook() {
    msg " * Quiting ssplash..."
    ssplash recover
}
