#!/bin/bash

build() {
    add_file "/etc/ssplash.conf"
    add_file "/lib/ssplash/splash.jpeg"
    add_binary "/sbin/ssplash"
    
    add_runscript
}

help() {
    cat <<HELPEOF
This hook will use trigger ssplash.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
